### ISSUE TITLE
Updating Ops/Whitelist

### ISSUE THREAD

**Issue by larrywright** [itzg/dockerfiles#89]
Currently there doesn't seem to be a way to update the whitelist of users by way of the WHITELIST environment variable - if the white-list.txt.converted file exists, the value of the WHITELIST environment variable is ignored. Is the intention that that variable is only for the initial setup, and then the whitelist.json file is maintained by hand after that?

Also, I've noticed that if you use either the WHITELIST or OPS environment variables, the first time the server is launched, they don't take effect. You have to shut down the server and start it back up and then the whitelisted users are able to log in. Is this a known issue?

**Comment by itzg** [comment]
Yes, @larrywright , as you speculated the environment variables are only intended for the first-time config of the whitelist and ops.

...however, what you have noticed wasn't a known bug, but I may have missed some cases of first start  vs second start and attached volumes.

How are you starting the container when you observe the WHITELIST and OPS not taking effect?

**Comment by larrywright** [comment]
I'm using this docker-compose file:

```
version: '2'
services:
  minecraft:
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "BUKKIT"
      VERSION: "1.10.2"
      WHITELIST: name1,name2
      OPS: name1,name2
      MODE: "creative"
      ENABLE_COMMAND_BLOCK: "true"
      ALLOW_NETHER: "true"
      FORCE_GAMEMODE: "false"
      HARDCORE: "false"
      SPAWN_ANIMALS: "true"
      SPAWN_MONSTERS: "true"
      SPAWN_NPCS: "true"
      PVP: "true"
      MAX_PLAYERS: 10
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      MAX_BUILD_HEIGHT: 500
      VIEW_DISTANCE: 50
      VM_OPTS: "-Xmx512M -Xms512M"
      MOTD: "My Minecraft server"
    image: itzg/minecraft-server
    container_name: minecraft
    stdin_open: true
    restart: always
    volumes:
      - minecraft-data:/data

volumes:
  minecraft-data:

```

**Comment by itzg** [comment]
Hmm, it might be a Bukkit-specific issue since tweaking your compose to run a vanilla server on 25566 processed the ops and whitelist properly. Can you see if you can confirm the same using (but change `itzg` to yourself :) ):

```
version: '2'
services:
  minecraft:
    ports:
      - "25566:25565"
    environment:
      EULA: "TRUE"
      VERSION: "1.10.2"
      WHITELIST: itzg
      OPS: itzg
      MODE: "creative"
      ENABLE_COMMAND_BLOCK: "true"
      ALLOW_NETHER: "true"
      FORCE_GAMEMODE: "false"
      HARDCORE: "false"
      SPAWN_ANIMALS: "true"
      SPAWN_MONSTERS: "true"
      SPAWN_NPCS: "true"
      PVP: "true"
      MAX_PLAYERS: 10
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      MAX_BUILD_HEIGHT: 500
      VIEW_DISTANCE: 50
      VM_OPTS: "-Xmx512M -Xms512M"
      MOTD: "My Minecraft server"
    image: itzg/minecraft-server
    container_name: minecraft-vanilla
    stdin_open: true
    restart: always
    volumes:
      - minecraft-vanilla-data:/data

volumes:
  minecraft-vanilla-data:
```

**Comment by larrywright** [comment]
Looks like your theory is correct. It works fine if I take out the TYPE: BUKKIT line.

I do see this in the console when I have that line in the first time the server starts up:

```
minecraft    | [14:24:01 INFO]: This server is running CraftBukkit version git-Bukkit-1628ce6 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)
minecraft    | [14:24:01 WARN]: Failed to load operators list: 
minecraft    | java.io.FileNotFoundException: ops.json (No such file or directory)
minecraft    | 	at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_91]
minecraft    | 	at java.io.FileInputStream.open(FileInputStream.java:195) ~[?:1.8.0_91]
minecraft    | 	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[?:1.8.0_91]
minecraft    | 	at com.google.common.io.Files.newReader(Files.java:86) ~[craftbukkit_server.jar:git-Bukkit-1628ce6]
minecraft    | 	at net.minecraft.server.v1_10_R1.JsonList.load(JsonList.java:171) ~[craftbukkit_server.jar:git-Bukkit-1628ce6]
minecraft    | 	at net.minecraft.server.v1_10_R1.DedicatedPlayerList.A(SourceFile:107) [craftbukkit_server.jar:git-Bukkit-1628ce6]
minecraft    | 	at net.minecraft.server.v1_10_R1.DedicatedPlayerList.<init>(SourceFile:29) [craftbukkit_server.jar:git-Bukkit-1628ce6]
minecraft    | 	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:183) [craftbukkit_server.jar:git-Bukkit-1628ce6]
minecraft    | 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:518) [craftbukkit_server.jar:git-Bukkit-1628ce6]
minecraft    | 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
minecraft    | [14:24:01 WARN]: Failed to load white-list: 
minecraft    | java.io.FileNotFoundException: whitelist.json (No such file or directory)
minecraft    | 	at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_91]
minecraft    | 	at java.io.FileInputStream.open(FileInputStream.java:195) ~[?:1.8.0_91]
minecraft    | 	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[?:1.8.0_91]
minecraft    | 	at com.google.common.io.Files.newReader(Files.java:86) ~[craftbukkit_server.jar:git-Bukkit-1628ce6]
minecraft    | 	at net.minecraft.server.v1_10_R1.JsonList.load(JsonList.java:171) ~[craftbukkit_server.jar:git-Bukkit-1628ce6]
minecraft    | 	at net.minecraft.server.v1_10_R1.DedicatedPlayerList.C(SourceFile:123) [craftbukkit_server.jar:git-Bukkit-1628ce6]
minecraft    | 	at net.minecraft.server.v1_10_R1.DedicatedPlayerList.<init>(SourceFile:30) [craftbukkit_server.jar:git-Bukkit-1628ce6]
minecraft    | 	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:183) [craftbukkit_server.jar:git-Bukkit-1628ce6]
minecraft    | 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:518) [craftbukkit_server.jar:git-Bukkit-1628ce6]
minecraft    | 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

**Comment by itzg** [comment]
Yeah, I noticed that too. I definitely remember that used to be output from the vanilla server, but isn't there with 1.10 at least. I'm wondering if there's some lag in the Bukkit code base...but I say that completely ignorant of how they decompile Minecraft.

**Comment by itzg** [comment]
Invalid json checking was fixed in f178c6c0a1dc47223720140ec77f4a3532582717

**Comment by mcrowson** [comment]
I'm having this issue still when running SPIGOT as the type. I suspect it is not picking up the json files.

```bash
bash-4.4# if [[ -z "ls *.json" ]]; then
>   echo "Checking JSON files"
>   for j in *.json; do
>     if [[ $(python -c "print open('$j').read().strip()==''") = True ]]; then
>       echo "Fixing JSON $j"
>       echo '[]' > $j
>     fi
>   done
> else
>   echo "Skipping JSON check. No files present."
> fi
Skipping JSON check. No files present.
bash-4.4# ls *.json
banned-ips.json      banned-players.json  ops.json             usercache.json       whitelist.json
```

I'm a bash noob, and i'm not sure what that leading -z argument does. If I remove it thought it successfully finds the JSON files, corrects them, and allows my whitelisted character to login.
